/* Generated By:JavaCC: Do not edit this line. testConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VOID = 1;
  /** RegularExpression Id. */
  int PROGRAM = 2;
  /** RegularExpression Id. */
  int IF = 3;
  /** RegularExpression Id. */
  int ELSE = 4;
  /** RegularExpression Id. */
  int WHILE = 5;
  /** RegularExpression Id. */
  int PRINT = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int CHAR = 9;
  /** RegularExpression Id. */
  int VECTOR = 10;
  /** RegularExpression Id. */
  int RETURN = 11;
  /** RegularExpression Id. */
  int EMPTY = 12;
  /** RegularExpression Id. */
  int cte_i = 13;
  /** RegularExpression Id. */
  int cte_f = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int cte_c = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"void\"",
    "\"Program\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"vector\"",
    "\"return\"",
    "\"\"",
    "<cte_i>",
    "<cte_f>",
    "<ID>",
    "<cte_c>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"&&\"",
    "\"<\"",
    "\">\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
    "\".\"",
  };

}
