/* Generated By:JavaCC: Do not edit this line. testConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 1;
  /** RegularExpression Id. */
  int IF = 2;
  /** RegularExpression Id. */
  int ELSE = 3;
  /** RegularExpression Id. */
  int WHILE = 4;
  /** RegularExpression Id. */
  int PRINT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int FLOAT = 7;
  /** RegularExpression Id. */
  int CHAR = 8;
  /** RegularExpression Id. */
  int VECTOR = 9;
  /** RegularExpression Id. */
  int RETURN = 10;
  /** RegularExpression Id. */
  int VOID = 11;
  /** RegularExpression Id. */
  int LBRACKET = 12;
  /** RegularExpression Id. */
  int RBRACKET = 13;
  /** RegularExpression Id. */
  int LKEY = 14;
  /** RegularExpression Id. */
  int RKEY = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int EMPTY = 17;
  /** RegularExpression Id. */
  int cte_i = 18;
  /** RegularExpression Id. */
  int cte_f = 19;
  /** RegularExpression Id. */
  int ID = 20;
  /** RegularExpression Id. */
  int cte_c = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Program\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"vector\"",
    "\"return\"",
    "\"void\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"\"",
    "<cte_i>",
    "<cte_f>",
    "<ID>",
    "<cte_c>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "\"\\\"\"",
  };

}
