PARSER_BEGIN(test)
import java.io.*;
class test 
{
	public static void main( String[] args )throws ParseException, Exception
	{
		try
		{		
     		test analizador = new test( System.in ) ;
			analizador.Programa();
			System.out.println("\tSuccessfully compiled");
		}
		catch(ParseException e)
		{
			System.out.println(e.getMessage());
			System.out.println("\tErrors found");
		}
	}
}
PARSER_END(test)

//palabras reservadas
TOKEN:
{
	<PROGRAM: "Program" >
	| <IF: "if" >
	| <ELSE: "else" >
	| <WHILE: "while" >
	| <PRINT: "print" >
	| <INT: "int" >
	| <FLOAT: "float" >
	| <CHAR: "char" >
	| <VECTOR: "vector" >
	| <RETURN: "return" >
	| <VOID: "void">
	| <LBRACKET: "[">
	| <RBRACKET: "]">
	| <LKEY: "{">
    | <RKEY: "}">
	| <SEMICOLON: ";">
	| <EMPTY: "">
}

TOKEN:
{
	<cte_i: ( ["0"-"9"] )+ >
	|<cte_f: ( ["0"-"9"] )+("."["0"-"9"])?  >
	|< ID: ["a"-"z","A"-"Z","_"] ( ["a"-"z","A"-"Z","_","0"-"9"] )* >
	|<cte_c :  ["a"-"z","A"-"Z","0"-"9","#"-"%"] >
	 
}

SKIP:
{
	" "|"\n" | "\r" | "\r\n" | "\t"
}

void Programa():
{}
{
	<PROGRAM> <ID> <SEMICOLON> Programa_AUX() <EOF>
}
void Programa_AUX():
{}
{
   (LOOKAHEAD(3) VARS())* (MODULO())* BLOQUE()
}

void BLOQUE():
{}
{
	(<LKEY> BLOQUE_AUX() <RKEY>)?
}

void BLOQUE_AUX():
{}
{
	ESTATUTO() (BLOQUE_AUX())? | <EMPTY>
}

void ESTATUTO():
{}
{
	LOOKAHEAD(3) VARS() | LOOKAHEAD(3) ASIGNACION() | CONDICION() | ESCRITURA() | CICLO() | LLAMADA_FUNC() | RETORNO()

}

void MEGAEXPRESION():
{}
{
	EXPRESION() MEGAEXPRESION_AUX()
}  

void MEGAEXPRESION_AUX():
{}
{ 
	((<"&&"> | <"||">) EXPRESION())?
}  

void EXPRESION():
{}
{
	EXP() (EXPRESION_AUX() EXP())?
}                                                  

void EXPRESION_AUX():
{}
{  
	<"<"> | <">"> | <"!=">
}

void EXP():
{}
{
	TERMINO() (LOOKAHEAD(3) EXP_AUX() EXP())?
}

void EXP_AUX():
{}
{  
	<"+"> | <"-">
}

void TERMINO():
{}
{
	FACTOR() (LOOKAHEAD(3) TERMINO_AUX() TERMINO())?
}

void TERMINO_AUX():
{}
{
	<"*"> | <"/">
}

void FACTOR():
{}
{
	<"("> MEGAEXPRESION() <")"> | (FACTOR_AUX())? VARCTE()
}

void FACTOR_AUX():
{}
{
	<"+"> | <"-">
}

void VARCTE():
{}
{
	<ID> (<LBRACKET> EXP() <RBRACKET>)? | <cte_i> | <cte_f>
}

void CONDICION():
{}
{
	<IF> <"("> MEGAEXPRESION() <")"> BLOQUE() CONDICION_AUX()
}

void CONDICION_AUX():
{}
{
	(<ELSE> (CONDICION() | BLOQUE()))?
}

void CICLO():
{}
{
	<WHILE> <"("> MEGAEXPRESION() <")"> BLOQUE() 
}

void VARS():
{}
{
	TIPO() (VARS_AUX1() | VARS_AUX2()) <SEMICOLON>
}

void VARS_AUX1():
{}
{
	<VECTOR> <ID> <LBRACKET> EXP() <RBRACKET> (<"="> <LKEY> VARS_AUX1_1() <RKEY>)?
}

void VARS_AUX1_1():
{}
{
	VARS_AUX2_1() (<","> (<"="> <LKEY> VARS_AUX1_1() <RKEY>)?)?
}

void VARS_AUX2():
{}
{
	<ID> (<"="> VARS_AUX2_1())? (<","> VARS_AUX2())?
}

void VARS_AUX2_1():
{}
{
	<cte_i> | <cte_f> | <cte_c> | <ID>
}

void MODULO():
{}
{
	MODULO_TIPO() <ID> <"("> MODULO_AUX() <")"> BLOQUE()
}

void MODULO_TIPO():
{}
{
	<VOID> | <INT> | <FLOAT> | <CHAR> | <VECTOR>
}

void MODULO_AUX():
{}
{
	(TIPO() <ID> (<","> MODULO_AUX())?)?
}

void RETORNO():
{}
{
	<RETURN> (LOOKAHEAD(3) VARCTE() | EXP()) <SEMICOLON>
}

void LLAMADA_FUNC():
{}
{
	<ID> <"("> LLAMADA_AUX() <")"> <SEMICOLON>
}

void LLAMADA_AUX():
{}
{
	(LLAMADA_PARAM() (<","> LLAMADA_AUX())?)?
}

void LLAMADA_PARAM():
{}
{
	LOOKAHEAD(3) <ID> | EXP()
}

void TIPO():
{}
{
	<INT> | <FLOAT> | <CHAR> 
}

void ASIGNACION():
{}
{
	<ID> <"="> EXP() <SEMICOLON>
}

void ESCRITURA():
{}
{
	<PRINT> <"("> ESCRITURA_AUX() <")"> <SEMICOLON>
}

void ESCRITURA_AUX():
{}
{
	EXP() (ESCRITURA_AUX())? | <"\""> (<cte_c> | VARCTE())* <"\"">
}